version: "3.8"

services:

    nginx:
        image: "nginx:stable-alpine"
        ports:
            - "8000:80"
        volumes:
            - ./_docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./:/var/www/laravel
        depends_on:
            - phpmyadmin
            - mysql
            - php

    php:
        build:
            dockerfile: _docker/dockerfiles/php.Dockerfile
        volumes:
            - ./:/var/www/laravel

    mysql:
        image: mysql:8.0
        ports:
            - "3316:3306"
        env_file:
            - ./_docker/env/mysql.env
        volumes:
            - ./_docker/db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        platform: linux/amd64
        ports:
            - "8080:80"
        env_file:
            - ./_docker/env/phpmyadmin.env

    composer:
        build:
            dockerfile: _docker/dockerfiles/composer.Dockerfile
        volumes:
            - ./:/var/www/laravel

    artisan:
        build:
            dockerfile: _docker/dockerfiles/php.Dockerfile
        volumes:
            - ./:/var/www/laravel
        entrypoint: ["php", "/var/www/laravel/artisan"]
